---

- name: Replace variables DOCKER_INTERFACE, DOCKER_NETWORK in /usr/sbin/sosetup
  become: yes
  become_user: root
  lineinfile: 
   path: /usr/sbin/sosetup
   regexp:  "{{ item.regexp }}"
   line: "{{ item.line }}"
   backup: yes
  with_items:
   - {regexp: '^DOCKER_INTERFACE=', line: 'DOCKER_INTERFACE="10.10.0.1"'}
   - {regexp: '^DOCKER_NETWORK=', line: 'DOCKER_NETWORK="10.10.0.0/24"'}


- name: Run SOSETUP with "{{ sosetupfilepath }}" in Master Node #Para el Master
  become: yes
  become_user: root
  expect:
   command: sosetup -y -f {{ sosetupfilepath }}
   timeout: 700 #modify timeout for command 
   responses:
     'Type yes to continue or anything else to exit.': "yes"
     'Are you sure you want to continue connecting.': "yes"
  register: sosetup_output
  when: "'master' in group_names"

- name: Run SOSETUP with "{{ sosetupfilepath }}" in Forward Node #Para el Forward
  become: yes
  become_user: root
  expect:
   command: sosetup -y -f {{ sosetupfilepath }}
   timeout: 700 #modify timeout for command 
   responses:
     'Type yes to continue or anything else to exit.': "yes"
     'Are you sure you want to continue connecting.': "yes"
     'password': "{{ admin_password }}" #si contiene la cadena password
  register: sosetup_output
  when: "'forward_nodes' in group_names"

- debug:
   var: sosetup_output

