---

   - name: Run SOSETUP with "{{ sosetupfilepath }}"
     expect:
       command: /home/sonionfce/holis.sh
       timeout: 30 #modify timeout for command 
       responses:
         "Are you sure you want to continue connecting": "yes"
         'password': "{{ so_ssh_master_password }}" #si contiene la cadena password
         '\n\s': "{{ so_ssh_master_password }}"
     register: sosetup_output

   - debug:
       var: sosetup_output


----------------------

#!/bin/bash
date >/home/sonionfce/holis.txt
read -p "sonionmaster@172.16.81.115's password: " password
echo $password
echo "Now try logging into the machine, with:   "ssh 'sonionmaster@172.16.81.115'"
and check to make sure that only the key(s) you wanted were added."
read -p " " aux
echo $aux
echo "termino"

