---


   - name: Install pexpect
     become: yes
     become_user: root
     apt:
      name: python-pexpect
      update_cache: yes

   - name: Run SOSETUP with "{{ sosetupfilepath }}"
     become: yes
     become_user: root
     expect:
       command: sosetup -y -f {{ sosetupfilepath }}
       timeout: 200 #modify timeout for command 
       responses:
         'Type yes to continue or anything else to exit.': "yes"
         'Are you sure you want to continue connecting.': "yes"
         'password': "{{ so_ssh_master_password }}" #si contiene la cadena password
     register: sosetup_output

   - debug:
       var: sosetup_output
