---

   - name: Run SOSETUP with "{{ sosetupfilepath }}" in Master Node #Para el Master
     become: yes
     become_user: root
     expect:
       command: sosetup -y -f {{ sosetupfilepath }}
       timeout: 600 #modify timeout for command 
       responses:
         'Type yes to continue or anything else to exit.': "yes"
         'Are you sure you want to continue connecting.': "yes"
         'password': "{{ BECOME_PASSWORD }}" #si contiene la cadena password
     register: sosetup_output
     when: "'master' in group_names"

   - name: Run SOSETUP with "{{ sosetupfilepath }}" in Forward Node #Para el Forward
     become: yes
     become_user: root
     expect:
       command: sosetup -y -f {{ sosetupfilepath }}
       timeout: 600 #modify timeout for command 
       responses:
         'Type yes to continue or anything else to exit.': "yes"
         'Are you sure you want to continue connecting.': "yes"
         'password': "{{ admin_password }}" #si contiene la cadena password
     register: sosetup_output
     when: "'forward_nodes' in group_names"

   - debug:
       var: sosetup_output
