es_host: elasticsearch
es_port: 9200

# (Required)
# Rule name, must be unique
index: "*:logstash-ids-*"
name: The Hive - Template Piority 1

type: any

filter:
- query_string:
    query: 'priority: "1" AND syslog-host: "sonion-forward-eco-ens160"'

alert: hivealerter

hive_connection:
  hive_host: http://172.16.81.115
  hive_port: 9000
  hive_apikey: 4bwfXyKyyFL7Nq7YacMCpTBPrXyJnGI4 #API key 

hive_proxies:
  http: ''
  https: ''

hive_alert_config:
  title: '{rule[name]} -- {match[alert]}'
  type: 'external'
  source: 'SecurityOnion'
  description: '{match[message]}'
  severity: 3
  tags: ['elastalert, SecurityOnion, {match[category]}']
  tlp: 3
  status: 'New'
  follow: True

hive_observable_data_mapping:
  - source_ip: '{match[source_ip]}'
  - destination_ip: '{match[destination_ip]}'
  - source_port: '{match[source_port]}'
  - destination_port: '{match[destination_port]}'
  - interface: '{match[interface]}'
  - timestamp: '{match[@timestamp]}'
  - classification: '{match[classification]}'
  - alert: '{match[alert]}'
  - category: '{match[category]}'
