---

- name: Run SOSETUP with "{{ sosetupfilepath }}" in Forward Node #Para el Forward
  become: yes
  become_user: root
  expect:
   command:
   timeout: 20 #modify timeout for command 
   responses:
    'Please enter your selection': "yes"
    'Are you sure you want to continue connecting.': "yes"
  register: sosetup_output





