---

- name: Allow Analyst ports 22/tcp, 443/tcp, and 7734/tcp for {{analyst_network}}
  become: yes
  become_user: root
  expect: 
   command: so-allow
   responses:
     'Please enter your selection': "a"
     'Please enter the IP address': "{{ analyst_network }}"
     'To continue and add this rule, press Enter.': "\r\n"
  when:  ' "{{ allow_analyst_network }}" in "yes" '
