---

- name: Copy TheHive Rules in /etc/elastalert/rules
  become: yes
  become_user: root
  copy:
    src: "{{ role_path }}/files/thehive_rules/" #from files folder roles"
    dest: /etc/elastalert/rules/
  when:  ' "{{ COPY_THEHIVE_RULES }}" in "yes" '

#find /etc/elastalert/rules -type f -exec sudo sed -i 's/\(hive_host: \)\(.*\)/\1REEMPLAZO/' {} \;
- name: Remplazo variables de hive_host de los archivos en /etc/elastalert/rules/ 
  become: yes
  become_user: root
  shell:  find /etc/elastalert/rules -type f -exec sudo sed -i 's/\(hive_host":" \)\(.*\)/\1R/' {} \;  
