- name: Install Security Onion
  hosts: all
#  become: yes
  gather_facts: yes

  vars_prompt:
#  - name: 'so_ssh_master_password'
#    prompt: 'SSH password for Security Onion Master'
#    private: yes
#    when: "'forward_nodes' in group_names"
   - name: 'forward_password_to_admin_user'
     prompt: 'Create a password for admin user in Forward Node and SSH password for Forward user created in Master Server '
     private: yes
     when: "'forward_nodes' in group_names"
  # when: 'not "forward_nodes" == group_names"'
 #  when: '"root" == ansible_user_id"'

  tasks:

    - name: Execute sosetup for forward
      include_role:
       name: securityonion_setup

