- name: Install Security Onion
  hosts: all
#  become: yes
  gather_facts: yes

  vars_prompt:

   - name: 'admin_password'
     prompt: 'Create a password used for "admincsirt" user created automatically [enter password]'
     private: yes

  tasks:

   - debug:
      msg: 
        - "The password entered will also be used to create a user on the Master Server." 
        - "The user created in the Master will have a username to the Forward Hostname."
        - "(if the user already exists, this password must match, otherwise the execution will fail)."
     when: "'forward_nodes' in group_names"
   
   - pause:
      seconds: 10

   - name: Execute sosetup for forward
     include_role:
      name: securityonion_setup


# when: 'not "forward_nodes" == group_names"'
# when: '"root" == ansible_user_id"'
# when: "'forward_nodes' in group_names"