- name: Install Security Onion
  hosts: all
#  become: yes
  gather_facts: yes

  vars_prompt:
   - name: 'forward_password_to_admin_user'
     prompt: 'Create a password used for "admin" user created in Forward Node and user created in Master Server for Forward [enter password]'
     private: yes
     when: "'forward_nodes' in group_names"
  # when: 'not "forward_nodes" == group_names"'
 #  when: '"root" == ansible_user_id"'

  tasks:

    - name: Execute sosetup for forward
      include_role:
       name: securityonion_setup

