
#agregar a sudo visudo al final
#soniontest ALL=(ALL) ALL


---

- name: Install Security Onion
  hosts: all
#  become: yes
  gather_facts: yes

  vars_prompt:
  - name: 'so_ssh_master_password'
    prompt: 'SSH password for Security Onion Master'
    private: yes
    when: "'forward_nodes' in group_names"
  - name: 'so_ssh_foward_pass_to_master'
    prompt: 'SSH password for Foward user created in Master Server'
    private: yes
    when: "'forward_nodes' in group_names"

  roles:
    - securityonion_setup

  
