---

#- debug:
#   var:  " '{{hive_host }}' | regex_replace('/', '\/') " #for sed command add "\/" for every "/" in http:// direction

- name: '[LOCALLY] Create a temporary folder for TheHive Rules in "/tmp/thehiverules-{{ ansible_hostname }}"'
  delegate_to: localhost 
  file: 
    path: "/tmp/thehiverules-{{ ansible_hostname }}-{{aux_name}}"
    state: directory
  register: thehiverules


- name: '[LOCALLY] copy rules to temporary folder' 
  delegate_to: localhost 
  copy:
    src: "{{ role_path }}/files/thehive_rules/" #from files folder roles
    dest: "{{ thehiverules.path }}"

# Create a new variable - Replace '/' for '\/' in "{{  hive_host }}" escape character
- set_fact:
    hive_host_escape:  "{{  hive_host | regex_replace( regexp1 , regexp2 ) }}"   # add "\/" for every "/" in http:// direction
  vars:
    regexp1: '/'
    regexp2: '\/'

# Create a new variable - Replace '/' for '\/' in "{{  hive_apikey }}" escape character
- set_fact:
    hive_apikey_escape:  "{{  hive_apikey | regex_replace( regexp1 , regexp2 ) }}"   # add "\/" for every "/" in http:// direction
  vars:
    regexp1: '/'
    regexp2: '\/'

#find /etc/elastalert/rules -type f -exec sudo sed -i 's/\(hive_host: \)\(.*\)/\1 REEMPLAZO/' {} \;
- name: '[LOCALLY] Replace the value hive_host for "{{ hive_host_escape }}:{{ hive_port }}" in all files in "{{ thehiverules.path }}"'
  delegate_to: localhost 
  shell: find "{{ thehiverules.path }}" -type f -exec sed -i 's/\(hive_host:\)\(.*\)/\1 {{ hive_host_escape }}:{{ hive_port }} /' {} \;
  #shell: find "{{ thehiverules.path }}" -type f -exec sed -i 's/\(hive_host:\)\(.*\)/\1 {{ hive_host_escape }} /' {} \;

#find /etc/elastalert/rules -type f -exec sudo sed -i 's/\(hive_port: \)\(.*\)/\1 REEMPLAZO/' {} \;
- name: '[LOCALLY] Replace the value hive_port for "{{ hive_port }}" in all files in "{{ thehiverules.path }}"'
  delegate_to: localhost 
  shell: find "{{ thehiverules.path }}" -type f -exec sed -i 's/\(hive_port:\)\(.*\)/\1 {{ hive_port }}/' {} \;

#find /etc/elastalert/rules -type f -exec sudo sed -i 's/\(hive_apikey: \)\(.*\)/\1 REEMPLAZO/' {} \;
- name: '[LOCALLY] Replace the value hive_apikey for "{{ hive_apikey_escape }}" in all files in "{{ thehiverules.path }}"'
  delegate_to: localhost 
  shell: find "{{ thehiverules.path }}" -type f -exec sed -i 's/\(hive_apikey:\)\(.*\)/\1 {{ hive_apikey_escape }}/' {} \;

- name: '[LOCALLY]  Search all files in "{{ thehiverules.path }}"'
  delegate_to: localhost 
  find:
   paths: "{{ thehiverules.path }}"
   recurse: yes
  register: rules_in_directory

- name: '[LOCALLY] Add "{{ ansible_hostname }}" in the field "name" of the rule'
  delegate_to: localhost 
  lineinfile:
    path: "{{ item.path }}"
    backrefs: yes
    regexp: '(^name:.*$)'
    line: '\1 - Node {{ ansible_hostname }}-{{aux_name}}'
  with_items: "{{ rules_in_directory.files }}" #para iterar sobre todas las reglas

- name: '[LOCALLY] Add "{{ansible_hostname}}" in the field "syslog-host" in "filter" section of the rule'
  delegate_to: localhost 
  replace:
    path: "{{ item.path }}"
    after:  'filter:'
    before: 'alert:'
    regexp: '(?<=\ syslog-host: ").+?(?=\")'
    replace: '{{ ansible_hostname }}'
  with_items: "{{ rules_in_directory.files }}" #para iterar sobre todas las reglas

- name: Change permisions in Master Node folder /etc/elastalert/rules in Master Node 
  delegate_to: localhost 
  command: ssh "{{ SSH_USERNAME }}"@"{{ SERVERNAME }}" 'sudo chmod 757 /etc/elastalert/rules'

- name: Copy TheHive Rules in Master Node folder /etc/elastalert/rules
  delegate_to: localhost
  command: scp -r "{{ thehiverules.path }}" {{ SSH_USERNAME }}@{{ SERVERNAME }}:/etc/elastalert/rules/

- name: Restore permisions in Master Node folder /etc/elastalert/rules
  delegate_to: localhost 
  command: ssh "{{ SSH_USERNAME }}"@"{{ SERVERNAME }}" 'sudo chmod 755 /etc/elastalert/rules/'











