---

#- debug:
#   var:  " '{{hive_host }}' | regex_replace('/', '\/') " #for sed command add "\/" for every "/" in http:// direction

- name: Create a folder for TheHive Rules
  file:
    path: "/home/{{ ansible_user_id }}/thehiverules"
    state: directory
    mode: '0755'
  register: thehiverules

  
- name: Copy TheHive Rules in "{{ thehiverules.path }}" Foward Node
  copy:
    src: "{{ role_path }}/files/thehive_rules/" #from files folder roles"
    dest: "{{ thehiverules.path }}"
- set_fact:
    http_hive_host:  "{{  hive_host | regex_replace( regexp1 , regexp2 ) }}"   #for sed command add "\/" for every "/" in http:// direction
  vars:
    regexp1: '/'
    regexp2: '\/'

#find /etc/elastalert/rules -type f -exec sudo sed -i 's/\(hive_host: \)\(.*\)/\1 REEMPLAZO/' {} \;
- name: Remplazo variables de hive_host de las reglas en "{{ thehiverules.path }}"
  become: yes
  become_user: root
  shell: find "{{ thehiverules.path }}" -type f -exec sudo sed -i 's/\(hive_host:\)\(.*\)/\1 {{ http_hive_host }} /' {} \;

#find /etc/elastalert/rules -type f -exec sudo sed -i 's/\(hive_port: \)\(.*\)/\1 REEMPLAZO/' {} \;
- name: Remplazo variables de hive_port de las reglas en "{{ thehiverules.path }}"
  become: yes
  become_user: root
  shell: find "{{ thehiverules.path }}" -type f -exec sudo sed -i 's/\(hive_port:\)\(.*\)/\1 {{ hive_port }}/' {} \;

#find /etc/elastalert/rules -type f -exec sudo sed -i 's/\(hive_apikey: \)\(.*\)/\1 REEMPLAZO/' {} \;
- name: Remplazo variables de hive_apikey de las reglas en "{{ thehiverules.path }}"
  become: yes
  become_user: root
  shell: find "{{ thehiverules.path }}" -type f -exec sudo sed -i 's/\(hive_apikey:\)\(.*\)/\1 {{ hive_apikey }}/' {} \;


- name: Create a zip archive of "{{ thehiverules.path }}"
  archive:
    path: "{{ thehiverules.path }}/*" 
    dest: "{{ thehiverules.path }}.zip" #create a file in home
    format: zip

- name: Change permisions in Master Node folder /etc/elastalert/rules
  expect: 
   command: ssh "{{ SSH_USERNAME }}"@"{{ SERVERNAME }}" 'sudo chmod 757 /etc/elastalert/rules'
   responses:
     'password': "{{ so_ssh_master_password }}"
     'Are you sure you want to continue connecting.': "yes"


- name: Copy TheHive Rules in Master Node folder /etc/elastalert/rules
  expect: 
   command: scp -r "{{ thehiverules.path }}.zip" {{ SSH_USERNAME }}@{{ SERVERNAME }}:/etc/elastalert/rules/
   responses:
     'password': "{{ so_ssh_master_password }}"
     'Are you sure you want to continue connecting.': "yes"


- name: Unzip "/etc/elastalert/rules/thehiverules.zip" in /etc/elastalert/rules Master Node
  expect: 
   command: ssh "{{ SSH_USERNAME }}"@"{{ SERVERNAME }}" 'sudo unzip /etc/elastalert/rules/thehiverules.zip -d /etc/elastalert/rules/'
   responses:
     'password': "{{ so_ssh_master_password }}"
     'Are you sure you want to continue connecting.': "yes"

- name: Remove "/etc/elastalert/rules/thehiverules.zip" in /etc/elastalert/rules Master Node
  expect: 
   command: ssh "{{ SSH_USERNAME }}"@"{{ SERVERNAME }}" 'sudo rm /etc/elastalert/rules/thehiverules.zip'
   responses:
     'password': "{{ so_ssh_master_password }}"
     'Are you sure you want to continue connecting.': "yes"

- name: Restore permisions in Master Node folder /etc/elastalert/rules
  expect: 
   command: ssh "{{ SSH_USERNAME }}"@"{{ SERVERNAME }}" 'sudo chmod 755 /etc/elastalert/rules/'
   responses:
     'password': "{{ so_ssh_master_password }}"
     'Are you sure you want to continue connecting.': "yes"


