
---

- name: Create a directory .ssh if it does not exist for user admin
  become: yes
  become_user: root
  file:
    path: /home/admincsirt/.ssh
    state: directory
    owner: admincsirt
    group: admincsirt
    mode: '0700'

- name: Copy authorized_keys from root to /home/admincsirt/.ssh/
  become: yes
  become_user: root
  copy:
    src: ~/.ssh/authorized_keys
    dest: /home/admincsirt/.ssh/authorized_keys
    remote_src: yes
    owner: admincsirt
    group: admincsirt
    mode: '0600'
